In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder

In [15]:
df = pd.read_csv('customer_churn.csv')

In [16]:
print(df.head() )

   CustomerID  Age  Gender  Tenure  Usage Frequency  Support Calls  \
0           1   22  Female      25               14              4   
1           2   41  Female      28               28              7   
2           3   47    Male      27               10              2   
3           4   35    Male       9               12              5   
4           5   53  Female      58               24              9   

   Payment Delay Subscription Type Contract Length  Total Spend  \
0             27             Basic         Monthly          598   
1             13          Standard         Monthly          584   
2             29           Premium          Annual          757   
3             17           Premium       Quarterly          232   
4              2          Standard          Annual          533   

   Last Interaction  Churn  
0                 9      1  
1                20      0  
2                21      0  
3                18      0  
4                18      0  


In [17]:
obj  = LabelEncoder()
for x in df.columns:
    if df[x].dtype in ['object', 'str']:
        df[x] = obj.fit_transform(df[x])

In [18]:
print(df.dtypes)

CustomerID           int64
Age                  int64
Gender               int64
Tenure               int64
Usage Frequency      int64
Support Calls        int64
Payment Delay        int64
Subscription Type    int64
Contract Length      int64
Total Spend          int64
Last Interaction     int64
Churn                int64
dtype: object


In [19]:
x = df.drop('Churn', axis=1).values
y = df['Churn'].values

In [20]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)   

In [21]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(51499, 11) (12875, 11) (51499,) (12875,)


In [22]:
# display the actual data

print("X_train data:\n", x_train)
print("X_test data:\n", x_test)
print("y_train data:\n", y_train)
print("y_test data:\n", y_test) 

X_train data:
 [[13469    56     0 ...     2   793    15]
 [20119    54     1 ...     2   610    24]
 [48412    31     1 ...     0   222    30]
 ...
 [  861    33     0 ...     2   454     6]
 [15796    24     1 ...     0   948    27]
 [56423    33     0 ...     2   554     2]]
X_test data:
 [[15477    55     1 ...     1   635    25]
 [34667    28     1 ...     2   631    10]
 [50475    65     0 ...     2   314     1]
 ...
 [55567    52     0 ...     2   871     6]
 [22750    20     0 ...     0   787    23]
 [31652    45     0 ...     1   503     2]]
y_train data:
 [0 0 1 ... 1 0 1]
y_test data:
 [0 0 1 ... 1 0 0]


In [23]:
# Scale features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)



In [ ]:
# Build model
clf = MLPClassifier(
    hidden_layer_sizes=(100,), 
    activation='relu',
    max_iter=500, 
    random_state=42, 
    verbose=True 
)

# Train model
clf.fit(x_train, y_train)

# Predict/evaluate
y_pred = clf.predict(x_test)

Iteration 1, loss = 0.38382503
Iteration 2, loss = 0.24083969
Iteration 3, loss = 0.20323352
Iteration 4, loss = 0.18273862
Iteration 5, loss = 0.16957791
Iteration 6, loss = 0.15967731
Iteration 7, loss = 0.15117086
Iteration 8, loss = 0.14379150
Iteration 9, loss = 0.13725558
Iteration 10, loss = 0.13153180
Iteration 11, loss = 0.12625062
Iteration 12, loss = 0.12158704
Iteration 13, loss = 0.11778295
Iteration 14, loss = 0.11408976
Iteration 15, loss = 0.11107178
Iteration 16, loss = 0.10820892
Iteration 17, loss = 0.10558347
Iteration 18, loss = 0.10295136
Iteration 19, loss = 0.10088377
Iteration 20, loss = 0.09896616
Iteration 21, loss = 0.09688464
Iteration 22, loss = 0.09554952
Iteration 23, loss = 0.09374138
Iteration 24, loss = 0.09243191
Iteration 25, loss = 0.09062027
Iteration 26, loss = 0.08914735
Iteration 27, loss = 0.08789179
Iteration 28, loss = 0.08655786
Iteration 29, loss = 0.08534370
Iteration 30, loss = 0.08409062
Iteration 31, loss = 0.08289720
Iteration 32, los